### ISSUE TITLE
Reason for removing fcn.py model (based on Kampffmeyer)

### ISSUE THREAD

**Issue by alexklibisz** [azavea/keras-semantic-segmentation#2]
It looks like you deleted the fcn.py model in [this commit](https://github.com/azavea/keras-semantic-segmentation/commit/abb7b9482cbcfe97fa7d43c96c5c066fa2602902).

Is there any specific reason for leaving that one out entirely? I personally found it useful as a starting point.

Thanks for your work in putting together these models.

**Comment by lewfish** [comment]
I had poor results with that model, and decided to try ResNets since I thought they would be easier to train. You're right that I should have kept the original model around. Later, I realized I had a bug in my data generators which was probably causing the poor results. I've just started working with these kinds of models, so wouldn't take anything in this repo as the gospel truth.

**Comment by alexklibisz** [comment]
Ok I see. Same here in terms of just starting with FCNs, etc. I suppose the link to the commit above can serve as reference to the original network.

I'll also mention the author name and paper URL so that it might come up on Google as a starting point for others wanting to implement that model: 

- URL: http://www.cv-foundation.org/openaccess/content_cvpr_2016_workshops/w19/papers/Kampffmeyer_Semantic_Segmentation_of_CVPR_2016_paper.pdf
- Paper title: Semantic Segmentation of Small Objects and Modeling of Uncertainty in Urban Remote Sensing Images Using Deep Convolutional Neural Networks
